server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j9d201.p.ssafy.io:8761/eureka
#      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9d201.p.ssafy.io:3306/member?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul
    username: root
#    password: ENC(0CubD7jkdnSKC4Yv2P7QCA==)
    password: ENC(1M5lYX7dirKF8nbCQIC4TFDM/wy8WlnM)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
#      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
#    host: ENC(cLuL/8Yyh4r2ZIcmYoan3gYdVLD+pEkd)
    host: j9d201.p.ssafy.io
    port: 6379
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 200MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(p3LG9Oa/HqfslQ2XoGFOSRLgf7rjffJJGO2L1upvJBJL/TI+MzhCnx+JsTPffrz3)
            client-secret: ENC(v6iYgpS27B8KbOzMxu1560mW4AWK1Bgoif6OcGaHEWqinWX5RJ1NfCfMyzf+vQ8D)
#            redirectUri: http://192.168.100.172:3000/auth
#            redirectUri: http://localhost:3000/auth
#            redirectUri: http://j9d201.p.ssafy.io:3000/meta/auth
            redirectUri: https://j9d201.p.ssafy.io/meta/auth
            authorization-grant-type: authorization_code
            client-name: kakao
            clientAuthenticationMethod: post
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ENC(PGC8tzpAs03EJrT/Ztn0B40bxy5fUsOohCIobEEaoedo+9yqI9dhrMN6VKN3rr5II7+bcLcYJTM=)

trace: true

springdoc:
  api-docs:
    path: /member-service/v3/api-docs
  swagger-ui:
    path: /member-service/swagger-ui.html

openapi:
  service:
    url: http://j9d201.p.ssafy.io:8000/
#    url: http://localhost:8000/

jasypt:
  encryptor:
    password: ${PASSWORD}


cloud:
  aws:
    s3:
      bucket: specialhaveit
    credentials:
      access_key: ENC(9c/7XqqcoGMoZ7k7+boajrpatZ0pdpeoJW/SUlHyX8U=)
      secret_key: ENC(nBDGhiZmrS6trcut4d5OYNRi4Q4Z07qghx9OHgjJc4ACIl5FC3imam59PTe8kN9GN2anlvvjWig=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false